### DISCUSSION TITLE
Changing pdf link on menu

### DISCUSSION THREAD

**Discussion by kyungnapark** [thegetty/quire#185] [Get Help] [answered]
How would I update the link to the PDF in the menu bar on the website so that it opens another URL?

**Comment by geealbers** [comment, marked as answer]
You'll find it in `data/publication.yml`:

```yaml
resource_link:
  - type: other-format
    name: PDF
    media_type: application/pdf
    link_relation: alternate
    url: /downloads/output.pdf
```

Anything listed under `resource_link` with a `type: other-format` will appear in the sidebar under the "Under Formats" heading. And the `name` and `url` can be anything you'd like.
