### DISCUSSION TITLE
.yaml shortcuts to import .csv files onto my website?

### DISCUSSION THREAD

**Discussion by annamorales5** [thegetty/quire#225] [Get Help]
Hello Quire community,

I have .csv files to organize the data that accompanies entries for my website design. I saw that there is a method for manually uploading data for each file entry/image on my site, but was wondering if anyone knows how to import .csv or similar formats through my text editor? Please let me know if you have any ideas and thank you in advance!

**Comment by geealbers** [comment]
Hi @annamorales5, you can't use csv directly in Quire, but luckily there are free online tools that will convert csv to yaml. Like https://onlineyamltools.com/convert-csv-to-yaml or https://www.convertcsv.com/csv-to-yaml.htm.

To get something that looks like this sample [object data](https://quire.getty.edu/documentation/collection-catalogues/#capture-object-data) in the Quire demo and documentation:

```yaml
object_list:
  - id: 2
    title: Impression, *Sunrise*
    artist: Claude Monet
    year: 1872
    medium: Oil on canvas
    dimensions: 48 cm × 63 cm (18.9 in × 24.8 in)
    location: Musée Marmottan Monet, Paris
```

You'd start with a csv file something like:

```csv
id,title,artist,year,medium,dimensions,location
2,"Impression, *Sunrise*",Claude Monet,1872,Oil on canvas,48 cm × 63 cm (18.9 in × 24.8 in),"Musée Marmottan Monet, Paris"
```

You'll probably still need to do some clean-up and maybe cutting and pasting, but it should get you pretty far.
