### DISCUSSION TITLE
Master Version Not Publishing

### DISCUSSION THREAD

**Discussion by aebancroft** [thegetty/quire#260] [Get Help] [answered]
Hello! I'm having issues publishing my essay. All my updates have been committed to the master branch of my essays Git repo. The [stage version](https://stage.museum-essays.getty.edu/photographs/cpeter-victorian-1/) appears correctly. And I do not get any error messages when running Quire preview; the [essay ](http://localhost:1313/photographs/cpeter-victorian-1/)appears correctly. However the [master link](https://museum-essays.getty.edu/photographs/cpeter-victorian-1/) for the essay throws a "page not found" error. 

This may very well be an issue with my hosting environment, but first I wanted to make sure I've exhausted all troubleshooting in Quire to rule that out as the issue. Any suggestions are welcome!

Thanks!

Alex

**Comment by geealbers** [comment, marked as answer]
Hi @aebancroft! I looked at the Netlify deploy logs and there's an error in another essay file that I think it breaking the build. If you look at https://github.com/thegetty/museum-essays/blob/master/content/photographs/awells-vroman.md you'll see it at the top in page YAML.

```yaml
---
weight: 200
type: entry
draft: false
<<<<<<< HEAD
title: "The Photographic Work of Adam Clark A.C. Vroman"
=======
title: "The Photographic Work of Adam Clark \"A.C.\" Vroman"
>>>>>>> dbade7e0d52559736503261230c5c6b86458c888
object:
  - id: 46430
pub_date: 2021-12-01
language: en
contributor:
  - id: adwells
---
```

That duplicate `title` and the other gobbledygook in there is from a merge conflict that happened somewhere along the way. If you fix that in the `master` branch to the following, I think you should find that the other essay builds properly as well:

```yaml
---
weight: 200
type: entry
draft: false
title: "The Photographic Work of Adam Clark \"A.C.\" Vroman"
object:
  - id: 46430
pub_date: 2021-12-01
language: en
contributor:
  - id: adwells
---
```

--- 

FYI, when you need quotes in a title like that, you can use the backslash to escape them as you did there, or you can use single quotes on the outer set:


```yaml
title: 'The Photographic Work of Adam Clark "A.C." Vroman'
```

Or, you can use unicode curly quotes:

```yaml
title: "The Photographic Work of Adam Clark “A.C.” Vroman"
```
