### DISCUSSION TITLE
Can I add markdown styling to a yaml block on ENTRY pages?

### DISCUSSION THREAD

**Discussion by kristhayer11** [thegetty/quire#449] [Get Help]
This is what I would like presented at the top of each entry page. Below is one of the more complicated entries (2 objects, not just one). I've tried various combinations of line breaks using html, slashes \ and pipes |. The yaml validator approves many of them, but the quire preview either displays incorrectly or produces an error. I know that custom css is probably the right way to do this (I don't want to change h1 globally...just for entry pages), but I haven't found the right css identifier to accomplish this. I am not opposed to inserting markdown styling on each entry page. Anyone have experience successfully adding md or html to yaml?

6–7. Adolphe Appian [line break]
*Landscape at Sunset* [ital] and [roman] *Woman Seated at the Edge of a Pond* [ital]

font-weight=400

This is one example of yaml that is "valid," but does not produce a line break. The itals do work, though:

---
label: 5. Ernest-André Andreas
title: |
  | *Houses in the Moonlight (Maisons au clair de lune)*
short_title:
weight: 211
class: side-by-side
object:
  - id: 143313
type: entry
abstract:
---

**Comment by geealbers** [comment]
Hi @kristhayer11, not sure I 100% follow, but would either of these options work:

```yaml
label: 6–7
title: "Adolphe Appian <br />*Landscape at Sunset* and *Woman Seated at the Edge of a Pond*"
```

```yaml
label: 6–7
title: |

  Adolphe Appian

  *Landscape at Sunset* and *Woman Seated at the Edge of a Pond*
```

Or, for something more robust that could give you the ability to fine tune for different contexts, you could wrap part of it in a classed `<span>` and then use some custom CSS. Something like:

```yaml
label: 6–7
title: "<span class="artist">Adolphe Appian</span> *Landscape at Sunset* and *Woman Seated at the Edge of a Pond*"
```

And add a comma when the title displays on single line:

```css
.artist::after { content: ","; }
```
And then remove the comma and make the `<span>` display on its own line when it's on an `entry-page`:

```css
.quire-entry .artist::after { content: ""; }
.quire-entry .artist { display: block; }
```

The actual CSS selectors probably need to be more specific, but hopefully this give you an idea.
