### DISCUSSION TITLE
In-text Citation Popup Rendering Error

### DISCUSSION THREAD

**Discussion by chrisdaaz** [thegetty/quire#637] [Get Help] [answered]
I'm using Quire `1.0.0-rc.0` on Windows 11.

I'm seeing some problems with rendering the in-text citation pop-ups. It seems that the text within the `class="quire-citation__content"` element is not ending up in the proper `<span>` element and is instead rendering directly on the page. 

The `short` or `id` of the citation will be linked in the rendered text, but there won't be any text in the popup. 

### HTML Result with `popupStyle: icon`:

_no click_

![image](https://user-images.githubusercontent.com/24395592/208570942-22f55c30-c423-4f3b-8a6e-be1885e37996.png)

_click_

![image](https://user-images.githubusercontent.com/24395592/208571846-a2cac723-183f-4442-8e22-f74769cfb5a5.png)

### HTML Result with `popupStyle: text`:

_no click_

![image](https://user-images.githubusercontent.com/24395592/208571279-5e77d5f8-e94d-45f2-992a-760e5917c1da.png)

_click_

![image](https://user-images.githubusercontent.com/24395592/208571337-f347af55-48d6-4a57-a367-b1b41223b851.png)

### Markdown:

```md
By situating Egyptian burial practices within the social setting of the interactions between living descendants and deceased ancestors, it may become easier to appreciate the central importance of the ancestor cult in ancient Egyptian society (E.g., {% cite 'Nyord 2018' %}, {% cite 'Weiss 2022' %}).
```

### YAML:
```yaml
entries:

  - id: "Nyord 2018"
    full: >
      Nyord, Rune. 2018. “'Taking ancient Egyptian mortuary religion seriously': Why would we, and how could we?” *Journal of Ancient Egyptian Interconnections* 17: 73-87.

  - id: "Weiss 2022"
    full: >
      Weiss, Lara. 2012. *The Walking Dead at Saqqara: Strategies of Social and Religious Interaction in Practice*. Berlin and Boston: De Gruyter.
```

Do you see any issues with my Markdown or YAML content? Thanks!

**Comment by geealbers** [comment]
HI @chrisdaaz, the issue stems from the YAML formatting you're using, and is the same for Window and macOS. The `>` character [indicates _block-level_ content](https://yaml.org/spec/1.2.2/#scalars) to follow and this is being rendered as a `<p>`, when it actually needs to be interpreted as a string and rendered as a `<span>` (since the citations will typically be made within block elements, and so can't be block elements themselves).

If you format the YAML like this, it should render correctly for you:

```yaml
entries:

  - id: "Nyord 2018"
    full: "Nyord, Rune. 2018. “'Taking ancient Egyptian mortuary religion seriously': Why would we, and how could we?” *Journal of Ancient Egyptian Interconnections* 17: 73-87."

  - id: "Weiss 2022"
    full: "Weiss, Lara. 2012. *The Walking Dead at Saqqara: Strategies of Social and Religious Interaction in Practice*. Berlin and Boston: De Gruyter."
```
Simply removing the `>` character and maintaining the line breaks and indenting should also work, as long as the strings are quoted in order to avoid the colons in the references being interpreted as YAML characters:

```yaml
entries:

  - id: "Nyord 2018"
    full: 
      "Nyord, Rune. 2018. “'Taking ancient Egyptian mortuary religion seriously': Why would we, and how could we?” *Journal of Ancient Egyptian Interconnections* 17: 73-87."

  - id: "Weiss 2022"
    full: 
      "Weiss, Lara. 2012. *The Walking Dead at Saqqara: Strategies of Social and Religious Interaction in Practice*. Berlin and Boston: De Gruyter."
```

I did some research to see if perhaps Quire's interpretation of the `>` character (and the same would go for the `|`) is incorrect, but from what I can tell, the character does specify that the content is a _block_ element, and so Quire is rendering it as expected. Let us know though if we should be reexamining this.
