### DISCUSSION TITLE
Using existing/external IIIF images in v1 project

### DISCUSSION THREAD

**Discussion by zsofiaj** [thegetty/quire#703] [Get Help] [answered]
Hi everyone! I’d like to be able to include external IIIF images in my Quire project, but I think the process has changed with v1. Would anyone be able to help with this? I have a list of urls for the IIIF manifest for each image. Those look like this:

https://manifests.collections.yale.edu/yuag/obj/45046

I tried pasting those into my figures.yaml file, but that didn't seem to do anything. The old IIIF instructions on the Quire documentation pages said to add /info.json to the end of the url above, and that would give me the complete json document. But that didn't seem to work. I'm new to working with IIIF Images, so I'm a little lost. I would be grateful for any help.

This is somewhat unrelated, but for some reason, the zoom function has not been working for my catalogued objects since I migrated to v1. I believe Erin and Greg are looking into this. In this example of a catalogue entry, you can see that the plus and minus buttons are gone at the top left of the image:

https://italian-paintings-march2023-updates.netlify.app/catalogue/volume-1/the-florentine-school/4/

**Comment by geealbers** [comment]
In v1, you can add external IIIF images by providing a manifest ID as well as the ID of a specific canvas within that manifest. IIIF IDs are typically URLs. For your example above, the YAML would look like this:

```yaml
  - id: "cat-4"
    manifestId: https://manifests.collections.yale.edu/yuag/obj/45046
    canvasId: https://manifests.collections.yale.edu/canvas/yuag/fb687417-fa46-4811-8f2e-d5955f5b3895
    caption: "Master of Varlungo, *Virgin and Child Enthroned with Two Angels*, ca. 1285–90"    
```

While the manifest is usually easy to identify as it's the top-level source for any IIIF image, finding the canvas requires looking inside the manifest. Start by opening the manifest URL in a browser. Depending on the browser and the formatting of the source manifest, you may be able to see the structure of the data in the file fairly easily. If it's all in a big blob, you can run it through any online JSON formatter to be able to read it better.

Once formatted, look for a grouping called `items` or `sequences`. Inside that there will be a list of one or more `canvases` and/or items with `type: Canvas`, and each of those should have an `id` that is a URL. Typically you'll use the `id` of the first canvas in the list (if there are more than one listed) as this is likely the main image. Other canvases listed could be things like the back or sides of the object, a special view, a single page within a multipage object, etc..

**One large caveat to all this:** Currently, Quire is not set up properly to be able to include a static version of an external IIIF resource like this for the PDF and EPUB output. This is something we still need to look at.
