### DISCUSSION TITLE
Adjusting image size/layout on a grid TOC page

### DISCUSSION THREAD

**Discussion by zsofiaj** [thegetty/quire#735] [Get Help] [answered]
I am curious if there is an easy way to adjust the image sizing on a grid contents page. Has anyone tried this? In my project, I have some images that are very narrow and tall, and others are very horizontal, so in the default layout, the horizontal objects end up looking tiny. We would like the objects to appear more equal in size, so it would be best if I could limit the size of each object by a max length for the longest side. Is that possible to do with custom css? I've attached a screenshot of one of our grid TOC pages.

I am working in Quire v 1.0.0-rc.7.

<img width="1433" alt="Screen Shot 2023-05-18 at 10 26 21 AM" src="https://github.com/thegetty/quire/assets/68071544/b29076ea-966d-4410-ad5b-78ba746e6980">

**Comment by geealbers** [comment, marked as answer]
In your custom.css file, you can set a fixed height for those images and then use "object-fit: contain;" which will scale each image to fill as much of the box as possible while still maintaining its aspect ratio:

```css
.quire-contents-list.grid .image img {
  height: 200px;
  object-fit: contain;
}
```

<img width="1374" alt="Screen Shot 2023-05-18 at 3 30 38 PM" src="https://github.com/thegetty/quire/assets/7796401/cbf34e5d-88eb-4681-8c29-12d9b7d69af2">

In think you'll then also want to remove the box shadow that appears on hover, as it will no longer fit the image borders properly and will look a little odd: 

```css
.quire-contents-list.grid ol li .card .card-image .image:hover {
  box-shadow: none;
}
```

**Reply by zsofiaj** [reply]
Thank you so much, @geealbers  , this is so much better, at least in terms of giving the objects more equal weight. It isn't quite as nice in terms of design, but I think our author will prefer it. Would it be easy enough to decrease the padding a bit, if we wanted the images to be slightly closer together?

**Reply by geealbers** [reply]
To adjust the spacing between items, you can play with this value:

```css
.quire-contents-list.grid ol li .card .card-image {
  padding: 0;
}
```
As well as maybe this one:

```css
.quire-contents-list.grid ol {
  grid-gap: 0;
}
```
