### DISCUSSION TITLE
Some images blank when outputting to PDF

### DISCUSSION THREAD

**Discussion by zsofiaj** [thegetty/quire#736] [Get Help]
When I output my project to pdf, my main catalogue entry images are showing up blank. All of the other figure images are showing up fine. When I tested outputting a pdf a few weeks ago, the images were there, but now they are gone. I do have IIIF links set up for those entry images (which are working fine in the html version of the book), so maybe it is related to that? There set of the comparative figures do not have IIIF links and they are just pulling from jpegs. But I do have fallback jpegs in place for the main entry images as well.

I am working in Quire v 1.0.0-rc.7.

Thank you!

**Comment by geealbers** [comment]
@zsofiaj for the entry images, you can specify a `printImage` in figures.yaml. Just note that you'll need to include `_assets/images/` as part of the path and you should also leave the `src` images in there as you have them now.

```yaml
  - id: "cat-1a"
    src: cats/cat_1_1871-1a_ag-obj-240-0001-pub-2000.jpg
    printImage: _assets/images/cats/cat_1_1871-1a_ag-obj-240-0001-pub-2000.jpg
    manifestId: https://manifests.collections.yale.edu/yuag/obj/240
    canvasId: https://manifests.collections.yale.edu/canvas/yuag/7fb8d1d2-140c-48e2-b343-89ff8c23ce0f
    caption: "Florentine School, *The Crucifixion,* One of Three Panels Panels from a Tabernacle Wing, ca. 1230"
    credit:
```

That should work, but let us know if not. And sorry it's a little wonky. As you know, Quire's support for external IIIF images isn't fully developed yet.
