### ISSUE TITLE
Figure identifiers must be lowercase, no spaces, etc, for scroll-to-lightbox-slide to work

### ISSUE THREAD

**Issue by cbutcosk** [thegetty/quire#869]
### Before proceeding, make sure there isn’t an existing issue for this bug.

- [X] I have searched the existing issues and determined this is a new bug.

### Expected Behavior

Adding images to `figures.yaml` that have uppercase letters, periods, or underscores I expect clicking on an image in the essay to still bring up that figure's slide in the lightbox modal. 

Or, if that's not going to work I expect it to break on build and tell me why. And I expect any constraints on figure identifiers to be documented. :)

### Actual Behavior

The figures are processed fine and appear in the essay but clicking on a figure brings you to the start of the lightbox rather than the slide of the figure you clicked. The only way I was able to get the spec data below to build was to replace figure identifiers' uppercase chars with lowercase and all periods / `.` with dashes (underscores as replacements did not work).

Note that the quire docs use a lot of figures with '.' in them!

### Steps to Reproduce

With this drawn-from-real data:
```yaml
  - id: "XXXX.1111.22"
    src: figures/XXXX_1111_22_FPO.jpg
    caption: "<cite>Work Title</cite>, Work Cataloguing Details. Various dimensions."
    credit: "ZZZZ © PHOTO CREDIT TK."
    zoom: true

  - id: "YYY-33333"
    src: figures/YYY-33333.jpg
    caption: "<cite>Another Work Title</cite>, 1980. Detailed cataloguing, Various dimensions."
    credit: "ZZZZ © PHOTO CREDIT TK."
    zoom: true
```

### Version Numbers

[CLI] Command 'info' called with options { debug: true }
[test-latest]
 quire-cli 1.0.0-rc.10
 quire-11ty 1.0.0-rc.14
 starter https://github.com/thegetty/quire-starter-default@2.6.0
[System]
 quire-cli 1.0.0-rc.10
 node v18.17.0
 npm 9.6.7
 os Darwin 22.6.0

### Web Browser

Platform: macOS, chrome: latest, safari: 17.0
